import express from 'express';
const router = express.Router();
import { registerUser, getAllUsers, getUserById, updateUser, deleteUser, loginUser } from '../controllers/authController.js';
router.post('/register', registerUser);
router.get('/', getAllUsers);
router.get('/:id', getUserById);
router.put('/:id', updateUser);
router.delete('/:id', deleteUser);
router.post('/login', loginUser);
export default router;