apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager 
      region: ap-south-1  
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: default
            
