apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-external-secret
  namespace: default
spec:
  refreshInterval: 1h  
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mongodb-credentials 
    creationPolicy: Owner
  data:
    - secretKey: mongo-uri  
      remoteRef:
        key: mongodb-uri  
        property: MONGO_URI

